// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXrwz_Pv5oDnrpJ5UYFX5WGSpiBtew4zw',
    appId: '1:775102597089:web:3a4ae3d6bbeb1e7070f4a0',
    messagingSenderId: '775102597089',
    projectId: 'ticheck',
    authDomain: 'ticheck.firebaseapp.com',
    storageBucket: 'ticheck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClNO0Ik690KFB50r3-rx0Ci9IEpwwREp0',
    appId: '1:775102597089:android:ac457581ea02f19170f4a0',
    messagingSenderId: '775102597089',
    projectId: 'ticheck',
    storageBucket: 'ticheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1zPoHp_NWCcdfhuhfQbBHeqcvy6squFs',
    appId: '1:775102597089:ios:581f9f2d675188f070f4a0',
    messagingSenderId: '775102597089',
    projectId: 'ticheck',
    storageBucket: 'ticheck.appspot.com',
    iosBundleId: 'com.example.ticheckgdscucb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1zPoHp_NWCcdfhuhfQbBHeqcvy6squFs',
    appId: '1:775102597089:ios:1b8ca9fa50f1d5b070f4a0',
    messagingSenderId: '775102597089',
    projectId: 'ticheck',
    storageBucket: 'ticheck.appspot.com',
    iosBundleId: 'com.example.ticheckgdscucb.RunnerTests',
  );
}
